export const DATA_LOAD_START = 'DATA_LOAD_START'
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS'
export const DATA_LOAD_ERROR = 'DATA_LOAD_ERROR'
export const DATA_LOAD_DELETE = 'DATA_LOAD_DELETE'

export const DATA_DISPLAY_PRODUCT = 'DATA_DISPLAY_PRODUCT'
