export const REG_START = 'REG_START'
export const REG_START_SUCCESS = 'REG_START_SUCCESS'
export const REG_START_ERROR = 'REG_START_ERROR'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS'
export const LOGIN_START_ERROR = 'LOGIN_START_ERROR'

export const LOGOUT = 'LOGOUT'