export const PRODUCT_LOAD_START = 'PRODUCT_LOAD_START'
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS'
export const PRODUCT_LOAD_ERROR = 'PRODUCT_LOAD_ERROR'
export const PRODUCT_LOAD_DELETE = 'PRODUCT_LOAD_DELETE'

export const PRODUCT_REVIEW_ADD_START = 'PRODUCT_REVIEW_ADD_START'
export const PRODUCT_REVIEW_ADD_SUCCESS = 'PRODUCT_REVIEW_ADD_SUCCESS'
export const PRODUCT_REVIEW_ADD_ERROR = 'PRODUCT_REVIEW_ADD__ERROR'
